# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filepile < Formula
  desc "Command-line client for a FilePile filesharing server"
  homepage "https://github.com/wilmervh/filepile-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WilmervH/filepile-cli/releases/download/v0.1.1/filepile_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "b488663fed2ef6804b81ff2818fe218c3be9a8c905ac16442eca223a85da074a"

      define_method(:install) do
        bin.install "filepile"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WilmervH/filepile-cli/releases/download/v0.1.1/filepile_0.1.1_Darwin_arm64.tar.gz"
      sha256 "fe5b50673e0d0c3104f6e6fc4495927d4b75e9d916901f9d86552ca8d0c778de"

      define_method(:install) do
        bin.install "filepile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WilmervH/filepile-cli/releases/download/v0.1.1/filepile_0.1.1_Linux_x86_64.tar.gz"
      sha256 "b964bab3ba2eacf54fb76c3471ae02ec63cd5e7d858e9f31d2945ed558af1185"
      define_method(:install) do
        bin.install "filepile"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WilmervH/filepile-cli/releases/download/v0.1.1/filepile_0.1.1_Linux_arm64.tar.gz"
      sha256 "3c8a9dba2ab30ad4475b16ee14016a0554dbd4c29ee08a4eb342c0d9fec7a86f"
      define_method(:install) do
        bin.install "filepile"
      end
    end
  end

  test do
    assert_match "filepile", shell_output("#{bin}/filepile --help")
  end
end
